<?php
function game_board_menu() {
  $items = array();
  $items['test_fields'] = array(
      'title' => 'test_fields',
      'page callback' => 'test_fields',
      'access arguments' => array('administer game entities'),
      'type' => MENU_LOCAL_ACTION,
  );
  return $items;
}
function _form_game_board_steps() {
  return array(
      1 => array(
          'title' => 'Step One',
          'form' => 'game_board_set_default_board',
      ),
      2 => array(
          'title' => 'Step Two',
          'form' => 'game_board_submit_this_board',
      )
  );
}

function game_board_set_default_board($form, $form_state, $form_id) {
  
}

function game_board_submit_this_board() {
  
}

function game_board_form_alter($form, $form_state, $form_id) {

  if ($form["#id"] == "game-ui-form" && $form['#bundle'] == "board_game") {
    if (empty($form_state['step'])) {
      $form_state['step'] = 1;
      $form_state['step_information'] = _form_game_board_steps();
    }
    //dpm($form);
    //dpm($form['actions']['submit']);
    $form['actions']['submit']["#value"] = "next step";
    $form['actions']['submit']["#submit"][0] = "game_board_set_default_board";

    /*
      $form['#next'] = array(
      '#type' => 'submit',
      '#value' => t('Next'),
      '#name' => 'next',
      '#submit' => array('game_board_set_default_board'),
      );
     */
    //$form['actions']['submit'] //$submit + array('game_ui_form_submit'),
    // dpm($form);
  }
}

//  Do something when Game Type Board is being saved is bean saved
function game_board_game_presave($game) {
  
}

function game_board_game_instance_presave($game_instance) {
  
}

/*
  function game_board_trigger_info() {
  return array(
  'game' => array(
  'game_board_tile_on_click' => array(
  'label' => t('When tile click event is called'),
  'type' => 'game',
  ),
  'game_board_tile_on_hover' => array(
  'label' => t('When tile hover event is called'),
  'type' => 'game',
  ),
  ),
  );
  }

  function game_board_action_info() {
  return array(
  'game_board_tile_set_owner_action' => array(
  'label' => t('Tile set owner'),
  'type' => 'game',
  'configurable' => TRUE,
  'triggers' => array('any', 'game'),
  ),
  );
  }
 */

function game_board_tile_set_owner_action(&$game_instance, $context = array()) {
  if ($context['game_id'] == $game_instance->gid) {

    $conditions = array("instance_id" => $game_instance->id, 'participant_session' => session_id());

    $entity = entity_load("game_instance_participant", FALSE, $conditions);
    $player = $entity[key($entity)];

    //dpm($player->participant_turn);
    // dpm($game_instance->field_matrix['und']);
    if ($game_instance->field_matrix['und'][$context['params']]['value'] == 0 || empty($game_instance->field_matrix['und'][$context['params']]['value'])) {
      $game_instance->field_matrix['und'][$context['params']]['value'] = $player->participant_turn;

      if ($game_instance->save()) {
        $params = array("tile_id" => $context['params'], "participant_turn" => $player->participant_turn);
        $game_instance_command = array();
        $game_instance_command['instance_id'] = $game_instance->id;
        $game_instance_command['command_id'] = 2;
        $game_instance_command['command_data'] = drupal_json_encode(array("message" => $context['message'], "callback" => array("module" => "boardGame", "fn" => $context['callback'], "params" => $params), "time" => time()));
        $game_instance_command_entity = entity_create("game_instance_command", $game_instance_command);
        $game_instance_command_entity->save();
      } else {

       // dpm("cant save game instance");
      }
    } else {
      // the tile is already owned by user cannot
      return array("callback" => array("module" => "gameInstance", "fn" => "message", "params" => array("The tile is already owned")));
      //dpm("the tile is already owned by user cannot");
    }


    //  dpm("got to action " . game_board_tile_set_owner_action);
  }
}

function game_board_tile_set_owner_action_form($context) {
  $games = entity_load('game');
  $string = array();

  foreach ($games as $key => $game) {
    $string[$key] = $game->label();
  }

  $form = array();

  $form['game_id'] = array(
      '#title' => t('The game'),
      '#type' => 'select',
      '#description' => t('the game this action will affect.'),
      '#options' => $string,
  );

  return $form;
}

function game_board_tile_set_owner_action_validate($form, $form_state) {
  //if (! $account = user_load_by_name($form_state['values']['author']) ) {
  //  form_set_error('author', t('Please, provide a valid username'));
  //}
}

function game_board_tile_set_owner_action_submit($form, $form_state) {

  return array('game_id' => $form_state['values']['game_id']);
}

function game_board_game_init_load($game) {
  if ($game->type == "board_game") {
    // add js
    $path = drupal_get_path('module', 'game_board');
    drupal_add_js($path . "/game_board.js", 'file');
    drupal_add_css($path . "/game_board.css", 'file');
  }
}

function game_board_tile_set_action_form($context) {
  $games = entity_load('game');
  $string = array();
  //dpm($games);
  foreach ($games as $key => $game) {
    $string[$key] = $game->label();
  }
  $form = array();

  $form['game_id'] = array(
      '#title' => t('The game'),
      '#type' => 'select',
      '#description' => t('the game this action will affect.'),
      '#options' => $string,
  );
  /*  $form['x_position'] = array(
    '#title' => t('tile x position'),
    '#type' => 'textfield',
    '#description' => t('the tile x position.'),
    );
    $form['y_position'] = array(
    '#title' => t('tile y position'),
    '#type' => 'textfield',
    '#description' => t('the tile y position.'),
    ); */
  /*
    $form['what_to_do'] = array(
    '#title' => t('That to do'),
    '#type' => 'option',
    '#description' => t('the tile y position.'),
    '#options' =>array("1"=>t('change binari state'),'2'=>'set tile belong to current player'),
    );
   */

  /*
    // Verify user permissions and provide an easier way to fill this field.
    if (user_access('access user profiles')) {
    $form['text']['#autocomplete_path'] = 'user/autocomplete';
    } */

  // No more options, return the form.
  return $form;
}

function game_board_tile_set_action_validate($form, $form_state) {
  //if (! $account = user_load_by_name($form_state['values']['author']) ) {
  //  form_set_error('author', t('Please, provide a valid username'));
  //}
}

function game_board_entity_property_info_alter(&$info) {
  $info['site']['properties']['current_tile_clicked'] = array(
      'label' => t('Current Tile clicked'),
      'type' => 'integer',
      'getter callback' => 'game_board_get_tile',
  );
}

/**
 * game_board_get_tile
 * gets tile from ajax loading 
 * @return type 
 */
function game_board_get_tile() {
  $tile_position = intval(check_plain($_POST['action']['params']['tile_position']));
  // chack valid tail position for current game
  return $tile_position;
}

function game_board_tile_set_action_submit($form, $form_state) {

  return array('game_id' => $form_state['values']['game_id']);
}
/**
 *  Game board default fields for Game and GameInstance entities of type game_board
 *  
 * @return string 
 */
function _game_board_default_fields() {
  $bundle = 'board_game';
  
  $fields = array();
  //  Fields for game entity
  $fields[] = array(
      'field_name' => 'field_start_condition',
      'label' => t('start condition'),
      'type' => 'text',
      'default_value' => '0',
      'cardinality' => FIELD_CARDINALITY_UNLIMITED,
      'entity_type' => 'game',
  );
  $fields[] = array(
      'field_name' => 'field_start_condition',
      'label' => t('start condition'),
      'type' => 'text',
      'default_value' => '0',
      'cardinality' => FIELD_CARDINALITY_UNLIMITED,
      'entity_type' => 'game',
  );
  $fields[] = array(
      'field_name' => 'field_board_width',
      'label' => t('Board Width'),
      'type' => 'text',
      'default_value' => '0',
      'cardinality' => '1',
      'entity_type' => 'game',
  );
  $fields[] = array(
      'field_name' => 'field_board_height',
      'label' => t('Board Height'),
      'type' => 'text',
      'default_value' => '0',
      'cardinality' => '1',
      'entity_type' => 'game',
  );
  $fields[] = array(
      'field_name' => 'field_min_num_players',
      'label' => t('Minmum Number Fields'),
      'type' => 'text',
      'default_value' => '0',
      'cardinality' => 1,
      'entity_type' => 'game',
      'settings' => array('target_type' => 'text', 'target_bundles' => array($bundle)),
  );
  $fields[] = array(
      'field_name' => 'field_max_num_players',
      'label' => t('Maximum Number Fields'),
      'type' => 'text',
      'default_value' => '0',
      'cardinality' => 1,
      'entity_type' => 'game',
      'settings' => array('target_type' => 'text', 'target_bundles' => array($bundle)),
  );  
  //  Fields for game insatnce
  $fields[] = array(
      'field_name' => 'field_matrix',
      'label' => t('Matrix'),
      'type' => 'text',
      'default_value' => '0',
      'cardinality' => FIELD_CARDINALITY_UNLIMITED,
      'entity_type' => 'game_instance',
      'settings' => array('target_type' => 'text', 'target_bundles' => array($bundle)),
  );
  $fields[] = array(
      'field_name' => 'field_players',
      'label' => t('Players'),
      'type' => 'entityreference',
      'default_value' => '0',
      'cardinality' => FIELD_CARDINALITY_UNLIMITED,
      'entity_type' => 'game_instance',
      'settings' => array('target_type' => 'text', 'target_bundles' => array($bundle)),
  );
  

  return $fields;
}

function _game_board_add_default_fields() {
  $bundle = 'board_game';
 // dpm("game_board_add_default_fields");
  
  $fields = _game_board_default_fields();
  foreach ($fields as $field) {
    //dpm($field);
    $field_info = field_info_field($field['field_name']);
    //dpm($field_info);
    if (!$field_info) {

      field_create_field($field);

      $instance = array(
          'field_name' => $field['field_name'],
          'label' => $field['label'],
          'entity_type' => $field['entity_type'],
          'bundle' => $bundle,
      );
      $instance += $field;

      field_create_instance($instance);
    }
  }
}

function _game_board_remove_default_fields() {
  
}
function test_fields() {
  _game_board_add_default_fields();
  return "";
}