<?php

function _game_sudoku_add_default_games() {
  $entity_type = "game";
  $bundle = 'board_game';

  $game = entity_create($entity_type, array());

  $game->title = "Sudoku";
  $game->type = $bundle;
  $game->machine_name = "sudoku";
  $game->description = 'Sudoku (数独 sūdoku?, すうどく) i/suːˈdoʊkuː/ soo-doh-koo, originally called Number Place,[1] is a logic-based,[2][3] combinatorial[4] number-placement puzzle. The objective is to fill a 9×9 grid with digits so that each column, each row, and each of the nine 3×3 sub-grids that compose the grid (also called "boxes", "blocks", "regions", or "sub-squares") contains all of the digits from 1 to 9. The puzzle setter provides a partially completed grid, which typically has a unique solution.';
  $game->field_board_dimension_amount['und'][0]['value'] = 9;
  $game->field_board_dimension_amount['und'][1]['value'] = 9;
  $game->field_min_num_players['und'][]['value'] = -1;
  $game->field_max_num_players['und'][]['value'] = -1;
  $game->field_tile_type['und'][]['value'] = 2;
  game_save($game);

}