<?php

function board_games_menu() {
  $items = array();
  $items['test_rules'] = array(
      'title' => 'test_rules',
      'page callback' => 'test_rules',
      'access arguments' => array('administer game entities'),
      'type' => MENU_LOCAL_ACTION,
  );
  return $items;
}

function _form_board_games_steps() {
  return array(
      1 => array(
          'title' => 'Step One',
          'form' => 'board_games_set_default_board',
      ),
      2 => array(
          'title' => 'Step Two',
          'form' => 'board_games_submit_this_board',
      )
  );
}

function board_games_set_default_board($form, $form_state, $form_id) {
  
}

function board_games_submit_this_board() {
  
}

function board_games_form_alter($form, $form_state, $form_id) {

  if ($form["#id"] == "game-ui-form" && $form['#bundle'] == "board_game") {
    if (empty($form_state['step'])) {
      $form_state['step'] = 1;
      $form_state['step_information'] = _form_board_games_steps();
    }

    $form['actions']['submit']["#value"] = "next step";
    $form['actions']['submit']["#submit"][0] = "board_games_set_default_board";

   
  }
}

//  Do something when Game Type Board is being saved is bean saved
function board_games_game_presave($game) {
  
}

function board_games_game_instance_presave($game_instance) {

  if ($game_instance->is_new && $game_instance->type == "board_game") {
    $game_instance->field_current_turn['und'][]["value"] = $game_instance->participant_turn;
    //game_instance_save($game_instance);
    //dpm($game_instance);
  }
}


function board_games_tile_set_owner_action(&$game_instance, $context = array()) {
  if ($context['game_id'] == $game_instance->gid) {

    $conditions = array("instance_id" => $game_instance->id, 'participant_session' => session_id());

    $entity = entity_load("game_instance_participant", FALSE, $conditions);
    $player = $entity[key($entity)];

    if ($game_instance->field_matrix['und'][$context['params']]['value'] == 0 || empty($game_instance->field_matrix['und'][$context['params']]['value'])) {
      $game_instance->field_matrix['und'][$context['params']]['value'] = $player->participant_turn;

      if ($game_instance->save()) {
        $params = array("tile_id" => $context['params'], "participant_turn" => $player->participant_turn);
        $game_instance_command = array();
        $game_instance_command['instance_id'] = $game_instance->id;
        $game_instance_command['command_id'] = 2;
        $game_instance_command['command_data'] = drupal_json_encode(array("message" => $context['message'], "callback" => array("module" => "boardGame", "fn" => $context['callback'], "params" => $params), "time" => time()));
        $game_instance_command_entity = entity_create("game_instance_command", $game_instance_command);
        $game_instance_command_entity->save();
      } else {

        // dpm("cant save game instance");
      }
    } else {
      // the tile is already owned by user cannot
      return array("callback" => array("module" => "gameInstance", "fn" => "message", "params" => array("The tile is already owned")));
      //dpm("the tile is already owned by user cannot");
    }


    //  dpm("got to action " . board_games_tile_set_owner_action);
  }
}

function board_games_tile_set_owner_action_form($context) {
  $games = entity_load('game');
  $string = array();

  foreach ($games as $key => $game) {
    $string[$key] = $game->label();
  }

  $form = array();

  $form['game_id'] = array(
      '#title' => t('The game'),
      '#type' => 'select',
      '#description' => t('the game this action will affect.'),
      '#options' => $string,
  );

  return $form;
}

function board_games_tile_set_owner_action_validate($form, $form_state) {
  //if (! $account = user_load_by_name($form_state['values']['author']) ) {
  //  form_set_error('author', t('Please, provide a valid username'));
  //}
}

function board_games_tile_set_owner_action_submit($form, $form_state) {

  return array('game_id' => $form_state['values']['game_id']);
}

function board_games_game_init_load($game) {
  if ($game->type == "board_game") {
    // add js
    $path = drupal_get_path('module', 'board_games');
    drupal_add_js($path . "/board_games.js", 'file');
    drupal_add_css($path . "/board_games.css", 'file');
  }
}

function board_games_tile_set_action_form($context) {
  $games = entity_load('game');
  $string = array();

  foreach ($games as $key => $game) {
    $string[$key] = $game->label();
  }
  $form = array();

  $form['game_id'] = array(
      '#title' => t('The game'),
      '#type' => 'select',
      '#description' => t('the game this action will affect.'),
      '#options' => $string,
  );
  /*  $form['x_position'] = array(
    '#title' => t('tile x position'),
    '#type' => 'textfield',
    '#description' => t('the tile x position.'),
    );
    $form['y_position'] = array(
    '#title' => t('tile y position'),
    '#type' => 'textfield',
    '#description' => t('the tile y position.'),
    ); */
  /*
    $form['what_to_do'] = array(
    '#title' => t('That to do'),
    '#type' => 'option',
    '#description' => t('the tile y position.'),
    '#options' =>array("1"=>t('change binari state'),'2'=>'set tile belong to current player'),
    );
   */

  /*
    // Verify user permissions and provide an easier way to fill this field.
    if (user_access('access user profiles')) {
    $form['text']['#autocomplete_path'] = 'user/autocomplete';
    } */

  // No more options, return the form.
  return $form;
}

function board_games_tile_set_action_validate($form, $form_state) {
  //if (! $account = user_load_by_name($form_state['values']['author']) ) {
  //  form_set_error('author', t('Please, provide a valid username'));
  //}
}

function board_games_entity_property_info_alter(&$info) {

  $info['site']['properties']['current_tile_clicked'] = array(
      'label' => t('Current Tile clicked'),
      'type' => 'integer',
      'getter callback' => 'board_games_get_tile',
  );
  $info['site']['properties']['current_tile_clicked_value'] = array(
      'label' => t('Current Tile clicked value'),
      'type' => 'integer',
      'getter callback' => 'board_games_get_tile_value',
  );
  $info['site']['properties']['current_player_id'] = array(
      'label' => t('Current player id'),
      'type' => 'integer',
      'getter callback' => 'board_games_get_player_id',
  );
  $info['site']['properties']['current_player_turn'] = array(
      'label' => t('Current player turn'),
      'type' => 'integer',
      'getter callback' => 'board_games_current_player_turn',
  );
  $info['site']['properties']['current_game_matrix'] = array(
      'label' => t('Current Tile clicked'),
      'type' => 'list<integer>', //number_integer
      'getter callback' => 'board_games_current_matrix',
  );
}

/**
 * board_games_get_tile
 * gets tile from ajax loading 
 * @return type 
 */
function board_games_get_tile() {
  $tile_position = intval(check_plain($_POST['action']['params']['tile_position']));
  // chack valid tail position for current game
  return $tile_position;
}

function board_games_get_player_id() {
  $session = session_id();
  $game_session = check_plain($_POST['action']['params']['session']);

  //dpm("GameSession: ".$session);
  //dpm("ParticipantSession: ".$game_session);

  $sql = "SELECT id FROM {game_instance} WHERE session=':gs'";
  $sql2 = str_replace(":gs", $game_session, $sql);
  //$result  = db_query($sql, array(":gs"=>$game_session));
  $result = db_query($sql2);
  $game_instance = $result->fetchObject();
  //dpm($game_instance->id);
  //  load current user session data
  $sql = "SELECT participant_turn FROM {game_instance_participant} WHERE instance_id=':gid' AND participant_session=':ses'";
  //$result  = db_query($sql, array(":gid"=>$game_instance->gid,"ses"=>$session));
  $sql2 = str_replace(":gid", $game_instance->id, $sql);
  $sql3 = str_replace(":ses", $session, $sql2);
  $result = db_query($sql3);

  $participant = $result->fetchObject();

  return $participant->participant_turn;
}

function board_games_current_player_turn() {
  $game_instance = _board_games_get_current_instance();
  return $game_instance->field_current_turn['und'][0]['value'];
}

function board_games_get_tile_value() {
  $tile_position = intval(check_plain($_POST['action']['params']['tile_position']));
  $game_instance = _board_games_get_current_instance();
  return $game_instance->field_matrix['und'][$tile_position]['value'];
}

function board_games_current_matrix() {
  //$game_instance = _board_games_get_current_instance();
  $game_session = check_plain($_POST['action']['params']['session']);
  //SELECT fm.field_matrix_value FROM game_instance gi LEFT JOIN field_revision_field_matrix fm ON (gi.id=fm.entity_id) WHERE gi.session='7b5c00a67c7e8a6247212c84dd38678c' ORDER BY delta ASC
  $sql = "SELECT field_revision_field_matrix.field_matrix_value FROM {game_instance} LEFT JOIN {field_revision_field_matrix} ON (game_instance.id=field_revision_field_matrix.entity_id) WHERE game_instance.session=':gs' ORDER BY delta ASC";
  $sql2 = str_replace(":gs", $game_session, $sql);
  $result = db_query($sql2);
  
  if(empty($result)) {
    return array();
  }
  $field_matrix = $result->fetchAll();
  foreach($field_matrix as $field) {
    $re[] = $field->field_matrix_value;
  }
  //dpm("field_matrix_value");
  //dpm($re);
  return $re;
}

function _board_games_get_current_instance($session = null) {
  if (empty($session)) {
    $session = check_plain($_POST['action']['params']['session']);
  }
  $conditions = array("session" => $session);
  game_instance_load();
  $e = entity_load('game_instance', array(), $conditions, FALSE);
  $k = array_keys($e);
  return $e[$k[0]];
}

function board_games_tile_set_action_submit($form, $form_state) {

  return array('game_id' => $form_state['values']['game_id']);
}

/**
 *  Game board default fields for Game and GameInstance entities of type board_games
 *  
 * @return string 
 */
function _board_games_default_fields() {
  $bundle = 'board_game';

  $fields = array();

  //  Fields for game entity
  $fields[] = array(
      'field_name' => 'field_board_width',
      'label' => t('Board Width'),
      'type' => 'number_integer',
      'default_value' => 0,
      'cardinality' => '1',
      'entity_type' => 'game',
  );
  $fields[] = array(
      'field_name' => 'field_board_height',
      'label' => t('Board Height'),
      'type' => 'number_integer',
      'default_value' => 0,
      'cardinality' => '1',
      'entity_type' => 'game',
  );
  $fields[] = array(
      'field_name' => 'field_min_num_players',
      'label' => t('Minmum Number Fields'),
      'type' => 'number_integer',
      'default_value' => 0,
      'cardinality' => 1,
      'entity_type' => 'game',
      'settings' => array('target_type' => 'text', 'target_bundles' => array($bundle)),
  );
  $fields[] = array(
      'field_name' => 'field_max_num_players',
      'label' => t('Maximum Number Fields'),
      'type' => 'number_integer',
      'default_value' => 0,
      'cardinality' => 1,
      'entity_type' => 'game',
      'settings' => array('target_type' => 'text', 'target_bundles' => array($bundle)),
  );
  //  Fields for game insatnce
  $fields[] = array(
      'field_name' => 'field_matrix',
      'label' => t('Matrix'),
      'type' => 'number_integer', //'number_integer',
      'default_value' => 0,
      'cardinality' => FIELD_CARDINALITY_UNLIMITED,
      'entity_type' => 'game_instance',
      'settings' => array('target_type' => 'text', 'target_bundles' => array($bundle)),
  );
  $fields[] = array(
      'field_name' => 'field_players',
      'label' => t('Players'),
      'type' => 'entityreference',
      // 'default_value' => '0',
      'cardinality' => FIELD_CARDINALITY_UNLIMITED,
      'entity_type' => 'game_instance',
          //'settings' => array('target_type' => 'text', 'target_bundles' => array($bundle)),
  );
  $fields[] = array(
      'field_name' => 'field_current_turn',
      'label' => t('Current Turn'),
      'type' => 'number_integer',
      'default_value' => 1,
      'cardinality' => 1,
      'entity_type' => 'game_instance',
      'settings' => array('target_type' => 'text', 'target_bundles' => array($bundle)),
  );
  return $fields;
}

function _board_games_add_default_fields() {
  $bundle = 'board_game';

  $fields = _board_games_default_fields();
  foreach ($fields as $field) {
    $field_info = field_info_field($field['field_name']);
    if (!$field_info) {

      field_create_field($field);

      $instance = array(
          'field_name' => $field['field_name'],
          'label' => $field['label'],
          'entity_type' => $field['entity_type'],
          'bundle' => $bundle,
      );
      $instance += $field;

      field_create_instance($instance);
    }
  }
}

function _board_games_add_default_games() {
  $entity_type = "game";
  $bundle = 'board_game';

  $game = entity_create($entity_type, array());

  $game->title = "TicTacToe";
  $game->type = $bundle;
  $game->description = "Tic-tac-toe (or Noughts and crosses, Xs and Os) is a pencil-and-paper game for two players, X and O, who take turns marking the spaces in a 3×3 grid. The player who succeeds in placing three respective marks in a horizontal, vertical, or diagonal row wins the game.";
  $game->field_board_width['und'][]['value'] = 3;
  $game->field_board_height['und'][]['value'] = 3;
  $game->field_min_num_players['und'][]['value'] = 2;
  $game->field_max_num_players['und'][]['value'] = 2;

  game_save($game);
  
}

function _board_games_remove_default_fields() {
  
}

function test_rules() {
  //_board_games_add_default_fields();
  //_board_games_add_default_games();
  $rule = '{ "rules_ticktacktoe_checkwinner" : {
    "LABEL" : "TickTackToe CheckWinner",
    "PLUGIN" : "rule set",
    "REQUIRES" : [ "rules", "game" ],
    "RULES" : [
      { "RULE" : {
          "IF" : [
            { "OR" : [
                { "data_is" : { "data" : [ "site:current-tile-clicked" ], "value" : "0" } },
                { "data_is" : { "data" : [ "site:current-tile-clicked" ], "value" : "1" } },
                { "data_is" : { "data" : [ "site:current-tile-clicked" ], "value" : "2" } }
              ]
            },
            { "data_is" : {
                "data" : [ "site:current-game-matrix:0" ],
                "value" : [ "site:current-game-matrix:1" ]
              }
            },
            { "data_is" : {
                "data" : [ "site:current-game-matrix:1" ],
                "value" : [ "site:current-game-matrix:2" ]
              }
            },
            { "data_is" : {
                "data" : [ "site:current-tile-clicked-value" ],
                "value" : [ "site:current-player-id" ]
              }
            }
          ],
          "DO" : [
            { "rules_game_set_winners" : {
                "game_instance_session" : [ "site:current-game-instance" ],
                "player_id" : [ "site:current-player-id" ]
              }
            },
            { "rules_game_over" : { "game_instance_session" : [ "site:current-game-instance" ] } }
          ],
          "LABEL" : "CheckMatrix row1"
        }
      },
      { "RULE" : {
          "IF" : [
            { "OR" : [
                { "data_is" : { "data" : [ "site:current-tile-clicked" ], "value" : "3" } },
                { "data_is" : { "data" : [ "site:current-tile-clicked" ], "value" : "4" } },
                { "data_is" : { "data" : [ "site:current-tile-clicked" ], "value" : "5" } }
              ]
            },
            { "data_is" : {
                "data" : [ "site:current-game-matrix:3" ],
                "value" : [ "site:current-game-matrix:4" ]
              }
            },
            { "data_is" : {
                "data" : [ "site:current-game-matrix:4" ],
                "value" : [ "site:current-game-matrix:5" ]
              }
            },
            { "data_is" : {
                "data" : [ "site:current-tile-clicked-value" ],
                "value" : [ "site:current-player-id" ]
              }
            }
          ],
          "DO" : [
            { "rules_game_set_winners" : {
                "game_instance_session" : [ "site:current-game-instance" ],
                "player_id" : [ "site:current-player-id" ]
              }
            },
            { "rules_game_over" : { "game_instance_session" : [ "site:current-game-instance" ] } }
          ],
          "LABEL" : "CheckMatrix row2"
        }
      },
      { "RULE" : {
          "IF" : [
            { "OR" : [
                { "data_is" : { "data" : [ "site:current-tile-clicked" ], "value" : "6" } },
                { "data_is" : { "data" : [ "site:current-tile-clicked" ], "value" : "7" } },
                { "data_is" : { "data" : [ "site:current-tile-clicked" ], "value" : "8" } }
              ]
            },
            { "data_is" : {
                "data" : [ "site:current-game-matrix:6" ],
                "value" : [ "site:current-game-matrix:7" ]
              }
            },
            { "data_is" : {
                "data" : [ "site:current-game-matrix:7" ],
                "value" : [ "site:current-game-matrix:8" ]
              }
            },
            { "data_is" : {
                "data" : [ "site:current-tile-clicked-value" ],
                "value" : [ "site:current-player-id" ]
              }
            }
          ],
          "DO" : [
            { "rules_game_set_winners" : {
                "game_instance_session" : [ "site:current-game-instance" ],
                "player_id" : [ "site:current-player-id" ]
              }
            },
            { "rules_game_over" : { "game_instance_session" : [ "site:current-game-instance" ] } }
          ],
          "LABEL" : "CheckMatrix row3"
        }
      },
      { "RULE" : {
          "IF" : [
            { "OR" : [
                { "data_is" : { "data" : [ "site:current-tile-clicked" ], "value" : "0" } },
                { "data_is" : { "data" : [ "site:current-tile-clicked" ], "value" : "3" } },
                { "data_is" : { "data" : [ "site:current-tile-clicked" ], "value" : "6" } }
              ]
            },
            { "data_is" : {
                "data" : [ "site:current-game-matrix:0" ],
                "value" : [ "site:current-game-matrix:3" ]
              }
            },
            { "data_is" : {
                "data" : [ "site:current-game-matrix:3" ],
                "value" : [ "site:current-game-matrix:6" ]
              }
            },
            { "data_is" : {
                "data" : [ "site:current-tile-clicked-value" ],
                "value" : [ "site:current-player-id" ]
              }
            }
          ],
          "DO" : [
            { "rules_game_set_winners" : {
                "game_instance_session" : [ "site:current-game-instance" ],
                "player_id" : [ "site:current-game-id" ]
              }
            },
            { "rules_game_over" : { "game_instance_session" : [ "site:current-game-instance" ] } }
          ],
          "LABEL" : "CheckMatrix col1"
        }
      },
      { "RULE" : {
          "IF" : [
            { "OR" : [
                { "data_is" : { "data" : [ "site:current-tile-clicked" ], "value" : "1" } },
                { "data_is" : { "data" : [ "site:current-tile-clicked" ], "value" : "4" } },
                { "data_is" : { "data" : [ "site:current-tile-clicked" ], "value" : "7" } }
              ]
            },
            { "data_is" : {
                "data" : [ "site:current-game-matrix:1" ],
                "value" : [ "site:current-game-matrix:4" ]
              }
            },
            { "data_is" : {
                "data" : [ "site:current-game-matrix:4" ],
                "value" : [ "site:current-game-matrix:7" ]
              }
            },
            { "data_is" : {
                "data" : [ "site:current-tile-clicked-value" ],
                "value" : [ "site:current-player-id" ]
              }
            }
          ],
          "DO" : [
            { "rules_game_set_winners" : {
                "game_instance_session" : [ "site:current-game-instance" ],
                "player_id" : [ "site:current-game-id" ]
              }
            },
            { "rules_game_over" : { "game_instance_session" : [ "site:current-game-instance" ] } }
          ],
          "LABEL" : "CheckMatrix col2"
        }
      },
      { "RULE" : {
          "IF" : [
            { "OR" : [
                { "data_is" : { "data" : [ "site:current-tile-clicked" ], "value" : "2" } },
                { "data_is" : { "data" : [ "site:current-tile-clicked" ], "value" : "5" } },
                { "data_is" : { "data" : [ "site:current-tile-clicked" ], "value" : "8" } }
              ]
            },
            { "data_is" : {
                "data" : [ "site:current-game-matrix:2" ],
                "value" : [ "site:current-game-matrix:5" ]
              }
            },
            { "data_is" : {
                "data" : [ "site:current-game-matrix:5" ],
                "value" : [ "site:current-game-matrix:8" ]
              }
            },
            { "data_is" : {
                "data" : [ "site:current-tile-clicked-value" ],
                "value" : [ "site:current-player-id" ]
              }
            }
          ],
          "DO" : [
            { "rules_game_set_winners" : {
                "game_instance_session" : [ "site:current-game-instance" ],
                "player_id" : [ "site:current-player-id" ]
              }
            },
            { "rules_game_over" : { "game_instance_session" : [ "site:current-game-instance" ] } }
          ],
          "LABEL" : "CheckMatrix col3"
        }
      }
    ]
  }
}';
  
  return "";
}
