<?php

function game_tictactoe_game_init_load($game, $running_game) {
  if ($game->type == "board_game" && $game->machine_name == 'tic-tac-toe') {
    $path = drupal_get_path('module', 'game_tictactoe');
    drupal_add_css($path . "/game_tictactoe.css", 'file');
  }
}

function _game_tictactoe_add_default_games() {
  $entity_type = "game";
  $bundle = 'board_game';

  $game = entity_create($entity_type, array());

  $game->title = "TicTacToe";
  $game->type = $bundle;
  $game->machine_name = "tic-tac-toe";
  $game->description = "Tic-tac-toe (or Noughts and crosses, Xs and Os) is a pencil-and-paper game for two players, X and O, who take turns marking the spaces in a 3×3 grid. The player who succeeds in placing three respective marks in a horizontal, vertical, or diagonal row wins the game.";
  $game->field_board_dimensions['und'][]['value'] = 2;
  $game->field_board_dimension_amount['und'][0]['value'] = 3;
  $game->field_board_dimension_amount['und'][1]['value'] = 3;
  $game->field_min_num_players['und'][]['value'] = 2;
  $game->field_max_num_players['und'][]['value'] = 2;
  $game->field_tile_type['und'][]['value'] = 1;

  game_save($game);
}

function _game_add_default_patterns() {
  $entity_type = 'game_pattern';
  $bundle = 'board_pattern';

  $pattern = entity_create($entity_type, array());

  $pattern->label = "Row";
  $pattern->machine_name = "row";
  $pattern->type = $bundle;
  $pattern->field_pattern[LANGUAGE_NONE][]['value'] = '{"start":{"x": "left","y": "py"},"end":{"x": "right","y": "py"}}';
  game_pattern_save($pattern);

  unset($pattern);
  $pattern = entity_create($entity_type, array());
  $pattern->label = "Column";
  $pattern->machine_name = "column";
  $pattern->type = $bundle;
  $pattern->field_pattern[LANGUAGE_NONE][]['value'] = '{"start":{"x": "px","y": "top"},"end":{"x": "px","y": "bottom"}}';
  game_pattern_save($pattern);

  unset($pattern);
  $pattern = entity_create($entity_type, array());
  $pattern->label = "Diagonal (top,left) (bottom,right)";
  $pattern->machine_name = "diagonal-topleft-bottomright";
  $pattern->type = $bundle;
  $pattern->field_pattern[LANGUAGE_NONE][]['value'] = '{"start":{"x": "left","offsetx":"1","y": "top","offsety":"1","repeat":"bottom"}}';
  game_pattern_save($pattern);

  unset($pattern);
  $pattern = entity_create($entity_type, array());
  $pattern->label = "Diagonal (top,right) (bottom,left)";
  $pattern->machine_name = "diagonal-topright-bottomleft";
  $pattern->type = $bundle;
  $pattern->field_pattern[LANGUAGE_NONE][]['value'] = '{"start":{"x": "right","offsetx":"-1","y": "top","offsety":"1","repeat":"bottom"}}';
  game_pattern_save($pattern);
}