<?php
/**
 * @file
 * basic setup needed to play tic tac toe
 */
/**
 * @function  Hook_install
 * when installing board games we want to add default fields and default games that comes with this module
 */
function game_tictactoe_install() {
  _game_tictactoe_add_default_games();
  _game_add_default_patterns();
}
function game_tictactoe_uninstall() {
  _game_tictactoe_remove_default_games();
}
function _game_tictactoe_remove_default_games() {
  
}
